    PROCESSOR 16f877a
    INCLUDE <p16f877a.inc>

valor1 equ 0x41
valor2 equ 0x42
valor3 equ 0x43

RANGO0 equ 0x32
RANGO1 equ 0x66
RANGO2 equ 0x99
RANGO3 equ 0xCA
RANGO4 equ 0xF5
RANGO5 equ 0xFF

RESULT equ 0x26   
    ORG 0
    GOTO INICIO
    ORG 5

INICIO:
    CALL    CONFIG_INICIAL
    MOVLW   0xE9        ; Selecciona el canal 0
    MOVWF   ADCON0
	MOVLW 	0x00
LOOP:
	MOVWF PORTD	

	CALL READ_PORT


	MOVLW	RANGO0
	SUBWF	RESULT, W ;RESULTADO - RANGO1- RESULTADO < RANGO1?
	BTFSC	STATUS,C
	GOTO 	COMP2 	
	
	MOVLW 0X00
	CALL PRINT_SS7

	GOTO LOOP	

COMP2
	MOVLW	RANGO1
	SUBWF	RESULT, W ;RESULTADO - RANGO1- RESULTADO < RANGO1?
	BTFSC	STATUS,C
	GOTO 	COMP3 	
	
	MOVLW 0X01
	CALL PRINT_SS7

	GOTO LOOP

COMP3
	MOVLW	RANGO2
	SUBWF	RESULT, W ;RESULTADO - RANGO1- RESULTADO < RANGO1?
	BTFSC	STATUS,C
	GOTO 	COMP4 	
	
	MOVLW 0X02
	CALL PRINT_SS7

	GOTO LOOP

COMP4
	MOVLW	RANGO3
	SUBWF	RESULT, W ;RESULTADO - RANGO1- RESULTADO < RANGO1?
	BTFSC	STATUS,C
	GOTO 	COMP5 	
	
	MOVLW 0X03
	CALL PRINT_SS7

	GOTO LOOP		

COMP5
	MOVLW	RANGO4
	SUBWF	RESULT, W ;RESULTADO - RANGO1- RESULTADO < RANGO1?
	BTFSC	STATUS,C
	GOTO 	COMP6 	
	
	MOVLW 0X04
	CALL PRINT_SS7

	GOTO LOOP

COMP6
	
	MOVLW 0X05
	CALL PRINT_SS7
			
	GOTO LOOP


READ_PORT:
	MOVLW   0x04
    IORWF   ADCON0,F    ; Enciende ADON y la bandera GO/DONE
    CALL    RET_200us
WAIT:
    BTFSC   ADCON0,2    ; Se revisa GO/DONE
    GOTO   	WAIT   		; Espera a la lectura
    
    MOVFW   ADRESH
	MOVWF   RESULT
    
	RETURN
    
PRINT_SS7
	
	ANDLW	0x07
	ADDWF	PCL,F

	RETLW    0x00
	RETLW 	 0X01
	RETLW 	 0X02
	RETLW 	 0X03
	RETLW    0X04
	RETLW 	 0X05
	RETLW    0x00
	RETLW    0x00
    
CONFIG_INICIAL:
    CLRF PORTA
	BCF     STATUS,RP1
	BSF     STATUS,RP0
	CLRF    TRISD
    CLRF    ADCON1
	BCF     STATUS,RP0
    ; Configura los pines del puerto A como entradas anal gicas.
    MOVLW   0xC0    ; Establece la frecuencia de muestreo
    MOVWF   ADCON0  ; como la interna del pic

	;Limpia los puertos
	CLRF    PORTD

	RETURN
	
RET_200us:
	MOVLW   0x02
	MOVWF   valor1
	MOVLW   0xA4
	MOVWF   valor2
	DECFSZ 	valor2
	GOTO 	$ - 1
	DECFSZ 	valor1
	GOTO 	$ - 5
	RETURN

    END